# Generated by Django 3.1.7 on 2022-05-16 17:47

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('staff_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('date_of_birth', models.DateField()),
                ('resume', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/media/resume'), upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
    ]
